### ISSUE TITLE
How can I change .obj files into .png files?

### ISSUE THREAD

**Issue by ZhangRuizhe2002** [RobertSmithers/3DTeethSegmentation#2]

**Comment by jytjyt05** [comment]
Hey ZhangRui, although our ultimate goal is to develop 3D model.
But rn we are still on the stage of dealing with 2D model. You may check pyTorch3D documentation to see how to read .obj file and transfer a view of 3D img to a 2D picture.

**Comment by ZhangRuizhe2002** [comment]
So how can I relate the labelling truth to the transformed 2D picture?

**Comment by jytjyt05** [comment]
Frankly, we don't understand the labelling truth either. This is why we giving up the 3D grandchallenge.

**Comment by ZhangRuizhe2002** [comment]
OK,thank you.

**Comment by ZhangRuizhe2002** [comment]
Could you please upload the dataset or just show the link of it?Thank u

**Comment by RobertSmithers** [comment]
The dataset we are using can be found in the [data folder](https://github.com/RobertSmithers/TeethSegmentation/tree/main/data). The 3D dataset can be found [from this challenge](https://3dteethseg.grand-challenge.org/). We (among multiple others) have already reached out to the organizers requesting clarification on the labels they have provided, but we are still waiting to hear back. 

For this reason, we are currently using our 2D data within the aforementioned folder until clarification is given.

Hope it helps!

**Comment by ZhangRuizhe2002** [comment]
Thanks for your reply!Could you please email me with the entire project code which I can run?I will be very grateful!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuting ***@***.***&gt;; 
发送时间: 2022年4月24日(星期天) 晚上9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RobertSmithers/3DTeethSegmentation] How can I change .obj files into .png files? (Issue #2)





 
Hey ZhangRui, although our ultimate goal is to develop 3D model.
 But rn we are still on the stage of dealing with 2D model. You may check pyTorch3D documentation to see how to read .obj file and transfer a view of 3D img to a 2D picture.
